import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7F9FC',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  backButton: {
    padding: 10,
  },
  menuButton: {
    padding: 10,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: 'Outfit-Bold',
    color: '#2D3748',
    fontWeight: '700',
  },
  scrollContent: {
    paddingBottom: 100,
  },
  profileHeader: {
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 20,
  },
  imageContainer: {
    width: 150,
    height: 150,
    borderRadius: 15,
    backgroundColor: '#fff',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    padding: 5,
    marginBottom: 30,
  },
  profileImage: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
  },
  name: {
    fontSize: 34,
    fontFamily: 'Outfit-Bold',
    color: '#1A202C',
    fontWeight: '800',
    textAlign: 'center',
    letterSpacing: -1,
  },
  title: {
    fontSize: 14,
    fontFamily: 'Outfit-Regular',
    color: '#4A5568',
    textAlign: 'center',
    marginTop: 5,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    fontWeight: '500',
  },
  headerBio: {
    fontSize: 15,
    fontFamily: 'Outfit-Regular',
    color: '#718096',
    textAlign: 'center',
    marginTop: 15,
    paddingHorizontal: 30,
    lineHeight: 22,
  },
  actionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 30,
  },
  actionCard: {
    width: (width - 55) / 2,
    backgroundColor: '#EDF2F7',
    borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  actionIconContainer: {
    marginRight: 10,
  },
  actionIcon: {
    fontSize: 20,
  },
  actionLabel: {
    fontSize: 14,
    fontFamily: 'Outfit-Bold',
    color: '#2D3748',
    fontWeight: '600',
  },
  infoSection: {
    paddingHorizontal: 20,
    marginTop: 20,
  },
  infoItem: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  infoIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#EDF2F7',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  infoIcon: {
    fontSize: 18,
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 12,
    color: '#718096',
    fontFamily: 'Outfit-Regular',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  infoValue: {
    fontSize: 16,
    color: '#2D3748',
    fontFamily: 'Outfit-Bold',
    fontWeight: '600',
    marginTop: 2,
  },
  qrSection: {
    paddingHorizontal: 20,
    marginTop: 20,
  },
  qrCardBase: {
    backgroundColor: '#EDF2F7',
    borderRadius: 20,
    paddingVertical: 30,
    alignItems: 'center',
  },
  qrCard: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 15,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    alignItems: 'center',
  },
  qrImage: {
    width: 200,
    height: 200,
    marginBottom: 15,
  },
  qrTextContainer: {
    alignItems: 'center',
    marginTop: 15,
  },
  qrTitle: {
    fontSize: 18,
    fontFamily: 'Outfit-Bold',
    color: '#2D3748',
    fontWeight: '700',
  },
  qrSubtitle: {
    fontSize: 12,
    fontFamily: 'Outfit-Regular',
    color: '#718096',
    marginTop: 4,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  aboutSection: {
    paddingHorizontal: 30,
    marginTop: 40,
  },
  aboutLabel: {
    fontSize: 12,
    fontFamily: 'Outfit-Bold',
    color: '#A0ABC0',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 3,
    marginBottom: 15,
  },
  aboutText: {
    fontSize: 16,
    fontFamily: 'Outfit-Regular',
    color: '#4A5568',
    lineHeight: 24,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    paddingVertical: 15,
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  addToContactsBtn: {
    flex: 1,
    backgroundColor: '#4A5568',
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    marginRight: 10,
  },
  btnIcon: {
    fontSize: 20,
    color: '#fff',
    marginRight: 10,
  },
  btnText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Outfit-Bold',
    fontWeight: '600',
  },
  shareBtn: {
    width: 60,
    backgroundColor: '#EDF2F7',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shareIcon: {
    fontSize: 20,
    color: '#4A5568',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  qrModalContainer: {
    width: '80%',
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 30,
    alignItems: 'center',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  qrModalTitle: {
    fontSize: 22,
    fontFamily: 'Outfit-Bold',
    color: '#2D3748',
    marginBottom: 20,
  },
  closeButton: {
    marginTop: 30,
    paddingVertical: 12,
    paddingHorizontal: 30,
    backgroundColor: '#EDF2F7',
    borderRadius: 10,
  },
  closeButtonText: {
    fontSize: 16,
    fontFamily: 'Outfit-Bold',
    color: '#4A5568',
  },
});
